[theme]
primaryColor = "#667eea"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#2a2a2a"
textColor = "#ffffff"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 